#!/bin/sh

set -o errexit
set -o nounset

# Remove a potentially stale celerybeat.pid file
rm -f /app/celerybeat.pid

celery -A config.celery beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
