# Generated by Django 6.0.1 on 2026-01-07 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Market Code')),
                ('name', models.CharField(max_length=100, verbose_name='Market Name')),
            ],
            options={
                'verbose_name': 'Market',
                'verbose_name_plural': 'Markets',
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='e.g., 600519', max_length=20, verbose_name='Symbol')),
                ('ts_code', models.CharField(help_text='e.g., 600519.SH', max_length=30, unique=True, verbose_name='Tushare Code')),
                ('name', models.CharField(max_length=255, verbose_name='Asset Name')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Asset Name')),
                ('name_zh_hans', models.CharField(max_length=255, null=True, verbose_name='Asset Name')),
                ('listing_status', models.CharField(choices=[('A', 'Active'), ('D', 'Delisted')], default='A', max_length=1, verbose_name='Listing Status')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='markets.market', verbose_name='Market')),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'unique_together': {('market', 'symbol')},
            },
        ),
        migrations.CreateModel(
            name='OHLCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('open', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Open')),
                ('high', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='High')),
                ('low', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Low')),
                ('close', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Close')),
                ('adj_close', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Adjusted Close')),
                ('volume', models.BigIntegerField(verbose_name='Volume')),
                ('amount', models.DecimalField(decimal_places=4, help_text='Turnover amount', max_digits=20, verbose_name='Amount')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ohlcv_data', to='markets.asset', verbose_name='Asset')),
            ],
            options={
                'verbose_name': 'OHLCV Data',
                'verbose_name_plural': 'OHLCV Data',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['asset', 'date'], name='markets_ohl_asset_i_b6bce1_idx')],
                'unique_together': {('asset', 'date')},
            },
        ),
    ]
