# Generated by Django 6.0.1 on 2026-04-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='list_date',
            field=models.DateField(blank=True, help_text='IPO/listing date from TuShare stock_basic', null=True, verbose_name='List Date'),
        ),
    ]