# Generated by Django 6.0.1 on 2026-04-27 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0002_asset_list_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='membership_tags',
            field=models.JSONField(blank=True, default=list, help_text='Current benchmark/index memberships, e.g. CSI300 and CSIA500.', verbose_name='Membership Tags'),
        ),
        migrations.CreateModel(
            name='IndexMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_code', models.CharField(db_index=True, max_length=20, verbose_name='Index Code')),
                ('index_name', models.CharField(max_length=100, verbose_name='Index Name')),
                ('trade_date', models.DateField(db_index=True, verbose_name='Trade Date')),
                ('weight', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='Weight')),
                ('source', models.CharField(default='tushare_index_weight', max_length=50, verbose_name='Source')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='index_memberships', to='markets.asset', verbose_name='Asset')),
            ],
            options={
                'verbose_name': 'Index Membership',
                'verbose_name_plural': 'Index Membership',
                'ordering': ['-trade_date', 'index_code', 'asset_id'],
                'indexes': [models.Index(fields=['index_code', 'trade_date'], name='markets_ind_index_c_47f1e6_idx'), models.Index(fields=['asset', 'index_code'], name='markets_ind_asset_i_13b97f_idx')],
                'unique_together': {('asset', 'index_code', 'trade_date')},
            },
        ),
    ]