# Generated by Django 6.0.1 on 2026-04-29 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0003_asset_membership_tags_indexmembership'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='indexmembership',
            new_name='markets_ind_index_c_eaead1_idx',
            old_name='markets_ind_index_c_47f1e6_idx',
        ),
        migrations.RenameIndex(
            model_name='indexmembership',
            new_name='markets_ind_asset_i_99c776_idx',
            old_name='markets_ind_asset_i_13b97f_idx',
        ),
    ]
