# Generated by Django 6.0.1 on 2026-09-13 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0011_remove_scheduled_model_retraining_tasks'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='assetsuspension',
            new_name='markets_ass_asset_i_efbcb2_idx',
            old_name='markets_ass_asset_i_8e3e4d_idx',
        ),
        migrations.RenameIndex(
            model_name='assetsuspension',
            new_name='markets_ass_trade_d_b11757_idx',
            old_name='markets_ass_trade_d_f467e2_idx',
        ),
        migrations.RenameIndex(
            model_name='benchmarkindexdaily',
            new_name='markets_ben_index_c_47622f_idx',
            old_name='markets_ben_index_c_786b2f_idx',
        ),
        migrations.RenameIndex(
            model_name='exchangetradingcalendar',
            new_name='markets_exc_exchang_6528c0_idx',
            old_name='markets_exc_exchang_1d4f01_idx',
        ),
        migrations.RenameIndex(
            model_name='pointintimebenchmarkdaily',
            new_name='markets_poi_benchma_265bb9_idx',
            old_name='markets_poi_benchma_8ab4b4_idx',
        ),
    ]
