services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: finance_analysis_django
    container_name: finance_analysis_django
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local
    ports:
      - "8000:8000"
    command: /start

  postgres:
    image: postgres:15-alpine
    container_name: finance_analysis_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=finance_analysis
      - POSTGRES_USER=finance_analysis
      - POSTGRES_PASSWORD=finance_analysis
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: finance_analysis_redis

  celery_worker:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: finance_analysis_django
    container_name: finance_analysis_celery_worker
    depends_on:
      - redis
      - postgres
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local
    command: /start-celeryworker

  celery_beat:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: finance_analysis_django
    container_name: finance_analysis_celery_beat
    depends_on:
      - redis
      - postgres
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local
    command: /start-celerybeat


volumes:
  postgres_data:
