services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: finance_analysis_django
    container_name: finance_analysis_django
    volumes:
      - .:/app
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    command: /start

  celery_worker:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: finance_analysis_django
    container_name: finance_analysis_celery_worker
    volumes:
      - .:/app
    env_file:
      - ./.env
    command: /start-celeryworker

  celery_beat:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: finance_analysis_django
    container_name: finance_analysis_celery_beat
    volumes:
      - .:/app
    env_file:
      - ./.env
    command: /start-celerybeat
