# Generated by Django 6.0.1 on 2026-04-12 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangelogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='Semantic version string, e.g. "1.1.0".', max_length=20, verbose_name='API Version')),
                ('release_date', models.DateField(verbose_name='Release Date')),
                ('change_type', models.CharField(choices=[('ADDED', 'Added'), ('CHANGED', 'Changed'), ('DEPRECATED', 'Deprecated'), ('REMOVED', 'Removed'), ('FIXED', 'Fixed'), ('SECURITY', 'Security')], default='ADDED', max_length=20, verbose_name='Change Type')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_breaking', models.BooleanField(default=False, help_text='Flag if this change is not backward-compatible.', verbose_name='Breaking Change')),
                ('endpoint', models.CharField(blank=True, help_text='e.g. "POST /api/v1/backtest/"', max_length=200, verbose_name='Affected Endpoint')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Changelog Entry',
                'verbose_name_plural': 'Changelog Entries',
                'ordering': ['-release_date', '-created_at'],
                'indexes': [models.Index(fields=['version'], name='developer_c_version_c5d3c1_idx'), models.Index(fields=['release_date'], name='developer_c_release_8a5ac7_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeveloperAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A friendly label for this key, e.g. "Production" or "CI pipeline".', max_length=100, verbose_name='Key Name')),
                ('key_prefix', models.CharField(editable=False, help_text='First 12 characters of the key (safe to display).', max_length=12, verbose_name='Key Prefix')),
                ('key_hash', models.CharField(editable=False, help_text='SHA-256 hash of the full key. Never stored in plain text.', max_length=64, unique=True, verbose_name='Key Hash')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_sandbox', models.BooleanField(default=False, help_text='Sandbox keys are limited to read-only operations and synthetic data.', verbose_name='Sandbox Mode')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Used At')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Leave blank for non-expiring keys.', null=True, verbose_name='Expires At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Developer API Key',
                'verbose_name_plural': 'Developer API Keys',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['key_hash'], name='developer_d_key_has_4705fc_idx'), models.Index(fields=['user', 'is_active'], name='developer_d_user_id_4655f7_idx')],
            },
        ),
    ]
