# Generated by Django 6.0.1 on 2026-04-12 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptHeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept_name', models.CharField(db_index=True, max_length=120, verbose_name='Concept Name')),
                ('date', models.DateField(db_index=True, verbose_name='Date')),
                ('heat_score', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='Heat Score')),
                ('article_count', models.PositiveIntegerField(default=0, verbose_name='Article Count')),
                ('up_limit_count', models.PositiveIntegerField(default=0, verbose_name='Up-Limit Count')),
                ('net_inflow', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='Net Inflow')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Concept Heat',
                'verbose_name_plural': 'Concept Heat',
                'ordering': ['-date', '-heat_score'],
                'unique_together': {('concept_name', 'date')},
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('EASTMONEY', 'Eastmoney'), ('TONGHUASHUN', 'Tonghuashun'), ('SINA', 'Sina Finance'), ('EXCHANGE', 'Exchange Announcement'), ('OTHER', 'Other')], default='OTHER', max_length=20, verbose_name='Source')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('url', models.URLField(max_length=1000, unique=True, verbose_name='URL')),
                ('published_at', models.DateTimeField(db_index=True, verbose_name='Published At')),
                ('content', models.TextField(blank=True, verbose_name='Content')),
                ('summary', models.TextField(blank=True, verbose_name='Summary')),
                ('language', models.CharField(default='zh', max_length=10, verbose_name='Language')),
                ('concept_tags', models.JSONField(blank=True, default=list, verbose_name='Concept Tags')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_assets', models.ManyToManyField(blank=True, related_name='news_articles', to='markets.asset')),
            ],
            options={
                'verbose_name': 'News Article',
                'verbose_name_plural': 'News Articles',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='SentimentScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Date')),
                ('score_type', models.CharField(choices=[('ARTICLE', 'Article Sentiment'), ('ASSET_7D', 'Asset 7D Aggregation'), ('MARKET_7D', 'Market 7D Aggregation')], db_index=True, max_length=20, verbose_name='Score Type')),
                ('positive_score', models.DecimalField(decimal_places=6, max_digits=7, verbose_name='Positive Score')),
                ('neutral_score', models.DecimalField(decimal_places=6, max_digits=7, verbose_name='Neutral Score')),
                ('negative_score', models.DecimalField(decimal_places=6, max_digits=7, verbose_name='Negative Score')),
                ('sentiment_score', models.DecimalField(decimal_places=6, max_digits=8, verbose_name='Sentiment Score')),
                ('sentiment_label', models.CharField(choices=[('POSITIVE', 'Positive'), ('NEUTRAL', 'Neutral'), ('NEGATIVE', 'Negative')], max_length=10, verbose_name='Sentiment Label')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sentiment_scores', to='sentiment.newsarticle')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sentiment_scores', to='markets.asset')),
            ],
            options={
                'verbose_name': 'Sentiment Score',
                'verbose_name_plural': 'Sentiment Scores',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='newsarticle',
            index=models.Index(fields=['source', 'published_at'], name='sentiment_n_source_925bdd_idx'),
        ),
        migrations.AddIndex(
            model_name='sentimentscore',
            index=models.Index(fields=['asset', 'date', 'score_type'], name='sentiment_s_asset_i_da9890_idx'),
        ),
        migrations.AddIndex(
            model_name='sentimentscore',
            index=models.Index(fields=['score_type', 'date'], name='sentiment_s_score_t_f189c4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sentimentscore',
            unique_together={('article', 'asset', 'date', 'score_type')},
        ),
    ]
