# Generated by Django 6.0.1 on 2026-04-12 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MacroSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True, verbose_name='Date')),
                ('dxy', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='US Dollar Index (DXY)')),
                ('cny_usd', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='CNY/USD')),
                ('cn10y_yield', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='China 10Y Yield')),
                ('cn2y_yield', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='China 2Y Yield')),
                ('pmi_manufacturing', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='PMI Manufacturing')),
                ('pmi_non_manufacturing', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='PMI Non-Manufacturing')),
                ('cpi_yoy', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='CPI YoY')),
                ('ppi_yoy', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='PPI YoY')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Macro Snapshot',
                'verbose_name_plural': 'Macro Snapshots',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='EventImpactStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_tag', models.CharField(db_index=True, max_length=100, verbose_name='Event Tag')),
                ('sector', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Sector')),
                ('horizon_days', models.PositiveIntegerField(default=20, verbose_name='Horizon Days')),
                ('avg_return', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Average Return')),
                ('excess_return', models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='Excess Return')),
                ('sample_size', models.PositiveIntegerField(default=0, verbose_name='Sample Size')),
                ('observations_start', models.DateField(blank=True, null=True, verbose_name='Observations Start')),
                ('observations_end', models.DateField(blank=True, null=True, verbose_name='Observations End')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Event Impact Statistic',
                'verbose_name_plural': 'Event Impact Statistics',
                'ordering': ['event_tag', 'sector', 'horizon_days'],
                'unique_together': {('event_tag', 'sector', 'horizon_days')},
            },
        ),
        migrations.CreateModel(
            name='MarketContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_key', models.CharField(db_index=True, default='current', max_length=50, verbose_name='Context Key')),
                ('macro_phase', models.CharField(choices=[('RECOVERY', 'Recovery'), ('OVERHEAT', 'Overheat'), ('STAGFLATION', 'Stagflation'), ('RECESSION', 'Recession')], db_index=True, max_length=20, verbose_name='Macro Phase')),
                ('event_tag', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Event Tag')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is Active')),
                ('starts_at', models.DateField(verbose_name='Starts At')),
                ('ends_at', models.DateField(blank=True, null=True, verbose_name='Ends At')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Market Context',
                'verbose_name_plural': 'Market Contexts',
                'ordering': ['-starts_at', '-updated_at'],
                'indexes': [models.Index(fields=['context_key', 'is_active'], name='macro_marke_context_dc83fc_idx'), models.Index(fields=['macro_phase', 'is_active'], name='macro_marke_macro_p_47186b_idx')],
            },
        ),
    ]
