# Generated by Django 6.0.1 on 2026-04-12 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapitalFlowSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Date')),
                ('northbound_net_5d', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='Northbound Net 5D')),
                ('northbound_net_10d', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='Northbound Net 10D')),
                ('northbound_net_20d', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='Northbound Net 20D')),
                ('main_force_net_5d', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='Main Force Net 5D')),
                ('margin_balance_change_5d', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='Margin Balance Change 5D')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capital_flow_snapshots', to='markets.asset', verbose_name='Asset')),
            ],
            options={
                'verbose_name': 'Capital Flow Snapshot',
                'verbose_name_plural': 'Capital Flow Snapshots',
                'indexes': [models.Index(fields=['asset', 'date'], name='factors_cap_asset_i_cac01a_idx'), models.Index(fields=['date'], name='factors_cap_date_7eb0ed_idx')],
                'unique_together': {('asset', 'date')},
            },
        ),
        migrations.CreateModel(
            name='FactorScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Date')),
                ('pe_percentile_score', models.DecimalField(blank=True, decimal_places=6, max_digits=7, null=True, verbose_name='PE Percentile Score')),
                ('pb_percentile_score', models.DecimalField(blank=True, decimal_places=6, max_digits=7, null=True, verbose_name='PB Percentile Score')),
                ('roe_trend_score', models.DecimalField(blank=True, decimal_places=6, max_digits=7, null=True, verbose_name='ROE Trend Score')),
                ('northbound_flow_score', models.DecimalField(blank=True, decimal_places=6, max_digits=7, null=True, verbose_name='Northbound Flow Score')),
                ('main_force_flow_score', models.DecimalField(blank=True, decimal_places=6, max_digits=7, null=True, verbose_name='Main Force Flow Score')),
                ('margin_flow_score', models.DecimalField(blank=True, decimal_places=6, max_digits=7, null=True, verbose_name='Margin Flow Score')),
                ('technical_reversal_score', models.DecimalField(blank=True, decimal_places=6, max_digits=7, null=True, verbose_name='Technical Reversal Score')),
                ('fundamental_score', models.DecimalField(decimal_places=6, default=0, max_digits=7, verbose_name='Fundamental Score')),
                ('capital_flow_score', models.DecimalField(decimal_places=6, default=0, max_digits=7, verbose_name='Capital Flow Score')),
                ('technical_score', models.DecimalField(decimal_places=6, default=0, max_digits=7, verbose_name='Technical Score')),
                ('financial_weight', models.DecimalField(decimal_places=4, default=0.4, max_digits=6, verbose_name='Financial Weight')),
                ('flow_weight', models.DecimalField(decimal_places=4, default=0.3, max_digits=6, verbose_name='Flow Weight')),
                ('technical_weight', models.DecimalField(decimal_places=4, default=0.3, max_digits=6, verbose_name='Technical Weight')),
                ('composite_score', models.DecimalField(decimal_places=6, default=0, max_digits=7, verbose_name='Composite Score')),
                ('bottom_probability_score', models.DecimalField(decimal_places=6, default=0, max_digits=7, verbose_name='Bottom Probability Score')),
                ('mode', models.CharField(choices=[('TECHNICAL', 'Technical'), ('FUNDAMENTAL', 'Fundamental'), ('COMPOSITE', 'Composite')], default='COMPOSITE', max_length=20, verbose_name='Mode')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factor_scores', to='markets.asset', verbose_name='Asset')),
            ],
            options={
                'verbose_name': 'Factor Score',
                'verbose_name_plural': 'Factor Scores',
                'ordering': ['-date', '-bottom_probability_score'],
                'indexes': [models.Index(fields=['date', 'mode', 'bottom_probability_score'], name='factors_fac_date_dafb3b_idx'), models.Index(fields=['asset', 'date'], name='factors_fac_asset_i_e85990_idx')],
                'unique_together': {('asset', 'date', 'mode')},
            },
        ),
        migrations.CreateModel(
            name='FundamentalFactorSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Date')),
                ('pe', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='PE')),
                ('pb', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='PB')),
                ('roe', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='ROE')),
                ('roe_qoq', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='ROE QoQ')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fundamental_factor_snapshots', to='markets.asset', verbose_name='Asset')),
            ],
            options={
                'verbose_name': 'Fundamental Factor Snapshot',
                'verbose_name_plural': 'Fundamental Factor Snapshots',
                'indexes': [models.Index(fields=['asset', 'date'], name='factors_fun_asset_i_5ffd01_idx'), models.Index(fields=['date'], name='factors_fun_date_d8aac6_idx')],
                'unique_together': {('asset', 'date')},
            },
        ),
    ]
