# Generated by Django 6.0.1 on 2026-04-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factorscore',
            name='sentiment_score',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=7, null=True, verbose_name='Sentiment Score'),
        ),
        migrations.AddField(
            model_name='factorscore',
            name='sentiment_weight',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=6, verbose_name='Sentiment Weight'),
        ),
    ]
