# Generated by Django 6.0.1 on 2026-04-25 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
        ('factors', '0002_factorscore_sentiment_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetMoneyFlowSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Date')),
                ('buy_sm_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='Small Buy Amount')),
                ('sell_sm_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='Small Sell Amount')),
                ('buy_md_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='Medium Buy Amount')),
                ('sell_md_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='Medium Sell Amount')),
                ('buy_lg_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='Large Buy Amount')),
                ('sell_lg_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='Large Sell Amount')),
                ('buy_elg_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='Extra Large Buy Amount')),
                ('sell_elg_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='Extra Large Sell Amount')),
                ('net_mf_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='Net Main Flow Amount')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='money_flow_snapshots', to='markets.asset', verbose_name='Asset')),
            ],
            options={
                'verbose_name': 'Asset Money Flow Snapshot',
                'verbose_name_plural': 'Asset Money Flow Snapshots',
                'unique_together': {('asset', 'date')},
                'indexes': [models.Index(fields=['asset', 'date'], name='factors_ass_asset_i_2c4a69_idx'), models.Index(fields=['date'], name='factors_ass_date_0b0ed1_idx')],
            },
        ),
        migrations.CreateModel(
            name='AssetMarginDetailSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Date')),
                ('rzye', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='Financing Balance')),
                ('rqye', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='Securities Lending Balance')),
                ('rzmre', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='Financing Buy Amount')),
                ('rzche', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='Financing Repayment Amount')),
                ('rqyl', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='Securities Lending Volume')),
                ('rqchl', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='Securities Lending Repayment Volume')),
                ('rqmcl', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='Securities Lending Sell Volume')),
                ('rzrqye', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='Margin Balance')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='margin_detail_snapshots', to='markets.asset', verbose_name='Asset')),
            ],
            options={
                'verbose_name': 'Asset Margin Detail Snapshot',
                'verbose_name_plural': 'Asset Margin Detail Snapshots',
                'unique_together': {('asset', 'date')},
                'indexes': [models.Index(fields=['asset', 'date'], name='factors_ass_asset_i_987fe7_idx'), models.Index(fields=['date'], name='factors_ass_date_98d7e0_idx')],
            },
        ),
    ]