# Generated by Django 6.0.1 on 2026-04-26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0003_assetmargindetailsnapshot_assetmoneyflowsnapshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capitalflowsnapshot',
            name='northbound_net_5d',
        ),
        migrations.RemoveField(
            model_name='capitalflowsnapshot',
            name='northbound_net_10d',
        ),
        migrations.RemoveField(
            model_name='capitalflowsnapshot',
            name='northbound_net_20d',
        ),
        migrations.RemoveField(
            model_name='factorscore',
            name='northbound_flow_score',
        ),
    ]