# Generated by Django 6.0.1 on 2026-01-07 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='Timestamp')),
                ('indicator_type', models.CharField(db_index=True, max_length=50, verbose_name='Indicator Type')),
                ('value', models.DecimalField(decimal_places=8, max_digits=18, verbose_name='Value')),
                ('parameters', models.JSONField(blank=True, default=dict, verbose_name='Parameters')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='markets.asset', verbose_name='Asset')),
            ],
            options={
                'verbose_name': 'Technical Indicator',
                'verbose_name_plural': 'Technical Indicators',
                'ordering': ['-timestamp', 'asset', 'indicator_type'],
                'indexes': [models.Index(fields=['asset', 'timestamp', 'indicator_type'], name='analytics_t_asset_i_836ba1_idx')],
                'unique_together': {('asset', 'timestamp', 'indicator_type', 'parameters')},
            },
        ),
    ]
