# Generated by Django 6.0.1 on 2026-04-12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenerTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('screener_type', models.CharField(choices=[('PREBUILT', 'Prebuilt'), ('CUSTOM', 'Custom')], default='CUSTOM', max_length=20, verbose_name='Screener Type')),
                ('config', models.JSONField(default=dict, verbose_name='Config')),
                ('is_public', models.BooleanField(default=False, verbose_name='Is Public')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='screener_templates', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Screener Template',
                'verbose_name_plural': 'Screener Templates',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['owner', 'is_public'], name='analytics_s_owner_i_99a362_idx'), models.Index(fields=['screener_type'], name='analytics_s_screene_35a92b_idx')],
            },
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('condition_type', models.CharField(choices=[('PRICE_ABOVE', 'Price Above'), ('PRICE_BELOW', 'Price Below'), ('INDICATOR_ABOVE', 'Indicator Above'), ('INDICATOR_BELOW', 'Indicator Below')], max_length=30, verbose_name='Condition Type')),
                ('indicator_type', models.CharField(blank=True, help_text='Required for indicator based alerts, e.g. RSI or MACD', max_length=50, verbose_name='Indicator Type')),
                ('threshold', models.DecimalField(decimal_places=8, max_digits=18, verbose_name='Threshold')),
                ('custom_condition', models.JSONField(blank=True, default=dict, verbose_name='Custom Condition')),
                ('channels', models.JSONField(default=list, help_text='Allowed channels: email, sms, websocket', verbose_name='Notification Channels')),
                ('cooldown_minutes', models.PositiveIntegerField(default=60, verbose_name='Cooldown Minutes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Triggered At')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='markets.asset', verbose_name='Asset')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Alert Rule',
                'verbose_name_plural': 'Alert Rules',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['owner', 'is_active'], name='analytics_a_owner_i_c596f0_idx'), models.Index(fields=['asset', 'is_active'], name='analytics_a_asset_i_930448_idx')],
            },
        ),
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('TRIGGERED', 'Triggered'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='TRIGGERED', max_length=20, verbose_name='Status')),
                ('trigger_value', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='Trigger Value')),
                ('message', models.TextField(verbose_name='Message')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('dispatched_channels', models.JSONField(blank=True, default=list, verbose_name='Dispatched Channels')),
                ('notified_at', models.DateTimeField(blank=True, null=True, verbose_name='Notified At')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='analytics.alertrule', verbose_name='Alert Rule')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_events', to='markets.asset', verbose_name='Asset')),
            ],
            options={
                'verbose_name': 'Alert Event',
                'verbose_name_plural': 'Alert Events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['alert_rule', 'created_at'], name='analytics_a_alert_r_9471f6_idx'), models.Index(fields=['status', 'created_at'], name='analytics_a_status_743f98_idx')],
            },
        ),
    ]
