# Generated by Django 6.0.1 on 2026-04-12 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_phase9_screeners_alerts'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='alertevent',
            new_name='analytics_a_alert_r_dda1a9_idx',
            old_name='analytics_a_alert_r_9471f6_idx',
        ),
        migrations.RenameIndex(
            model_name='alertevent',
            new_name='analytics_a_status_bf4a95_idx',
            old_name='analytics_a_status_743f98_idx',
        ),
        migrations.RenameIndex(
            model_name='alertrule',
            new_name='analytics_a_owner_i_9bb608_idx',
            old_name='analytics_a_owner_i_c596f0_idx',
        ),
        migrations.RenameIndex(
            model_name='alertrule',
            new_name='analytics_a_asset_i_c62397_idx',
            old_name='analytics_a_asset_i_930448_idx',
        ),
        migrations.RenameIndex(
            model_name='screenertemplate',
            new_name='analytics_s_owner_i_371aba_idx',
            old_name='analytics_s_owner_i_99a362_idx',
        ),
        migrations.RenameIndex(
            model_name='screenertemplate',
            new_name='analytics_s_screene_d141a8_idx',
            old_name='analytics_s_screene_35a92b_idx',
        ),
    ]
