# Generated by Django 6.0.1 on 2026-04-12 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_rename_analytics_a_alert_r_9471f6_idx_analytics_a_alert_r_dda1a9_idx_and_more'),
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(choices=[('GOLDEN_CROSS', 'Golden Cross (MA5 crosses above MA20)'), ('DEATH_CROSS', 'Death Cross (MA5 crosses below MA20)'), ('MA_BULL_ALIGN', 'Bull MA Alignment (MA5 > MA10 > MA20 > MA60)'), ('MA_BEAR_ALIGN', 'Bear MA Alignment (MA5 < MA10 < MA20 < MA60)'), ('BB_SQUEEZE', 'Bollinger Band Squeeze (Low Volatility)'), ('BB_BREAKOUT_UP', 'Price Breakout Above Upper Band'), ('BB_BREAKOUT_DOWN', 'Price Breakout Below Lower Band'), ('BB_RSI_OVERBOUGHT', 'Overbought: Upper Band + RSI > 70'), ('BB_RSI_OVERSOLD', 'Oversold: Lower Band + RSI < 30'), ('VOLUME_SPIKE', 'Volume Spike (> 2x 20-day Average)'), ('VOLUME_PRICE_DIVERGENCE', 'Volume-Price Divergence'), ('MOMENTUM_UP_5D', 'Strong 5-Day Upward Momentum (> +5%)'), ('MOMENTUM_DOWN_5D', 'Strong 5-Day Downward Momentum (< -5%)'), ('HIGH_RS_SCORE', 'High Relative Strength Score (Top 20%)'), ('OVERSOLD_COMBINATION', 'Oversold: RSI + Lower BB + Volume Contraction')], db_index=True, max_length=50, verbose_name='Signal Type')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='Timestamp')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signal_events', to='markets.asset', verbose_name='Asset')),
            ],
            options={
                'verbose_name': 'Signal Event',
                'verbose_name_plural': 'Signal Events',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['asset', 'timestamp', 'signal_type'], name='analytics_s_asset_i_754716_idx'), models.Index(fields=['signal_type', 'timestamp'], name='analytics_s_signal__f4fd22_idx')],
                'unique_together': {('asset', 'timestamp', 'signal_type')},
            },
        ),
    ]
