# Generated by Django 6.0.1 on 2026-04-12 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('markets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('strategy_type', models.CharField(choices=[('BOTTOM_CANDIDATE', 'Bottom Candidate'), ('PREDICTION_THRESHOLD', 'Prediction Threshold'), ('MACRO_ROTATION', 'Macro Rotation')], db_index=True, default='PREDICTION_THRESHOLD', max_length=40, verbose_name='Strategy Type')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20, verbose_name='Status')),
                ('start_date', models.DateField(db_index=True, verbose_name='Start Date')),
                ('end_date', models.DateField(db_index=True, verbose_name='End Date')),
                ('initial_capital', models.DecimalField(decimal_places=2, default=100000, max_digits=18, verbose_name='Initial Capital')),
                ('cash', models.DecimalField(decimal_places=2, default=100000, max_digits=18, verbose_name='Cash')),
                ('final_value', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Final Value')),
                ('total_return', models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='Total Return')),
                ('annualized_return', models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='Annualized Return')),
                ('max_drawdown', models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='Max Drawdown')),
                ('sharpe_ratio', models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='Sharpe Ratio')),
                ('win_rate', models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='Win Rate')),
                ('total_trades', models.PositiveIntegerField(default=0, verbose_name='Total Trades')),
                ('winning_trades', models.PositiveIntegerField(default=0, verbose_name='Winning Trades')),
                ('parameters', models.JSONField(blank=True, default=dict, verbose_name='Parameters')),
                ('report', models.JSONField(blank=True, default=dict, verbose_name='Report')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backtest_runs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Backtest Run',
                'verbose_name_plural': 'Backtest Runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BacktestTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_date', models.DateField(db_index=True, verbose_name='Trade Date')),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], db_index=True, max_length=10, verbose_name='Side')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='Quantity')),
                ('price', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Price')),
                ('fee', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Fee')),
                ('slippage', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Slippage')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='Amount')),
                ('pnl', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='PnL')),
                ('signal_payload', models.JSONField(blank=True, default=dict, verbose_name='Signal Payload')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtest_trades', to='markets.asset', verbose_name='Asset')),
                ('backtest_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='backtest.backtestrun', verbose_name='Backtest Run')),
            ],
            options={
                'verbose_name': 'Backtest Trade',
                'verbose_name_plural': 'Backtest Trades',
                'ordering': ['trade_date', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='backtestrun',
            index=models.Index(fields=['strategy_type', 'status', 'created_at'], name='backtest_ba_strateg_09a3c6_idx'),
        ),
        migrations.AddIndex(
            model_name='backtestrun',
            index=models.Index(fields=['start_date', 'end_date'], name='backtest_ba_start_d_7aa3d1_idx'),
        ),
        migrations.AddIndex(
            model_name='backtesttrade',
            index=models.Index(fields=['backtest_run', 'trade_date'], name='backtest_ba_backtes_b45f5e_idx'),
        ),
        migrations.AddIndex(
            model_name='backtesttrade',
            index=models.Index(fields=['asset', 'trade_date'], name='backtest_ba_asset_i_07fdc1_idx'),
        ),
    ]
