# Generated by Django 6.0.1 on 2026-09-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0002_backtestrun_lifecycle_controls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backtestrun',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20, verbose_name='Status'),
        ),
    ]
